"""empty message

Revision ID: 7917d13d6cf9
Revises: 4c067e2a1740
Create Date: 2018-06-22 16:37:35.014637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7917d13d6cf9'
down_revision = '4c067e2a1740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
